const constants = {
    ADD_KEYWORD : "ADD_KEYWORD",
    DELETE_KEYWORD : "DELETE_KEYWORD",
    FETCH_HASHTAGS : "FETCH_HASHTAGS",
    CANCEL_FETCHING: "CANCEL_FETCHING",
    ADD_HASHTAGS : "ADD_HASHTAGS",
    REMOVE_HASHTAGS: "REMOVE_HASHTAGS",
    INIT_SUGGESTED_TAGS: "INIT_SUGGESTED_TAGS",
    ADD_SUGGESTED_TAGS: "ADD_SUGGESTED_TAGS",
    DELETE_SUGGESTED_TAGS: "DELETE_SUGGESTED_TAGS",
    RESET_SUGGESTED_TAGS: "RESET_SUGGESTED_TAGS",
    RESET_RECOMMENDED_TAGS: "REST_RECOMMENDED_TAGS" // only use when fetching data
}

export default constants;